name: Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php_version }})
    strategy:
      fail-fast: false
      matrix:
        php_version: [8.2, 8.3, 8.4]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-php-${{ matrix.php_version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php_version }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: composer test
